// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0Bb07bF8Y2ddklxfE0gMAnvM8dk8Iuhk',
    appId: '1:552246178500:web:2c590cde42dac0dc3fcf91',
    messagingSenderId: '552246178500',
    projectId: 'homedesignia-55072',
    authDomain: 'homedesignia-55072.firebaseapp.com',
    databaseURL: 'https://homedesignia-55072-default-rtdb.firebaseio.com',
    storageBucket: 'homedesignia-55072.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA49n8NwLIor4El1IO7pwmK-HemZF-XCM',
    appId: '1:552246178500:android:375861efeb61825d3fcf91',
    messagingSenderId: '552246178500',
    projectId: 'homedesignia-55072',
    databaseURL: 'https://homedesignia-55072-default-rtdb.firebaseio.com',
    storageBucket: 'homedesignia-55072.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfkQUyWHsHWIDmNDFLDN2Ly4jH_RIq2SY',
    appId: '1:552246178500:ios:4dbda328ea54e92d3fcf91',
    messagingSenderId: '552246178500',
    projectId: 'homedesignia-55072',
    databaseURL: 'https://homedesignia-55072-default-rtdb.firebaseio.com',
    storageBucket: 'homedesignia-55072.firebasestorage.app',
    iosClientId: '552246178500-qtabq82je56llnkooiik7c4ecj27s1uu.apps.googleusercontent.com',
    iosBundleId: 'com.example.interior',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfkQUyWHsHWIDmNDFLDN2Ly4jH_RIq2SY',
    appId: '1:552246178500:ios:4dbda328ea54e92d3fcf91',
    messagingSenderId: '552246178500',
    projectId: 'homedesignia-55072',
    databaseURL: 'https://homedesignia-55072-default-rtdb.firebaseio.com',
    storageBucket: 'homedesignia-55072.firebasestorage.app',
    iosClientId: '552246178500-qtabq82je56llnkooiik7c4ecj27s1uu.apps.googleusercontent.com',
    iosBundleId: 'com.example.interior',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0Bb07bF8Y2ddklxfE0gMAnvM8dk8Iuhk',
    appId: '1:552246178500:web:a76924acd02877853fcf91',
    messagingSenderId: '552246178500',
    projectId: 'homedesignia-55072',
    authDomain: 'homedesignia-55072.firebaseapp.com',
    databaseURL: 'https://homedesignia-55072-default-rtdb.firebaseio.com',
    storageBucket: 'homedesignia-55072.firebasestorage.app',
  );

}